
var songs = [
    {"title":"12-BAR ORIGINAL"                      , "writer":"Lennon, McCartney, Harrison and Starkey     ", "vocalist":"*Instrumental*                               "},
//A
    {"title":"ACROSS THE UNIVERSE"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"ACT NATURALLY"	                    , "writer":"Russell, Morrison                           ", "vocalist":"Starkey                                      "},
    {"title":"AIN'T SHE SWEET"	                    , "writer":"Yellen, Ager	                            ", "vocalist":"Lennon	                                    "},
    {"title":"ALL I'VE GOT TO DO"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon                                       "},
    {"title":"ALL MY LOVING"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney                                    "},
    {"title":"ALL THINGS MUST PASS"	                , "writer":"Harrison	                                ", "vocalist":"*Instrumental*                               "},
    {"title":"ALL TOGETHER NOW"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"ALL YOU NEED IS LOVE"	                , "writer":"Lennon                                      ", "vocalist":"Lennon                                       "},
    {"title":"AND I LOVE HER"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"AND YOUR BIRD CAN SING"               , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"ANNA (GO TO HIM)"	                    , "writer":"Alexander	                                ", "vocalist":"Lennon	                                    "},
    {"title":"ANOTHER GIRL"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"ANY TIME AT ALL"	                    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"ASK ME WHY"	                        , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon 	                                    "},
//B
    {"title":"BABY IT'S YOU"	                    , "writer":"Bacharach, David, Dixon	                    ", "vocalist":"Lennon	                                    "},
    {"title":"BABY, YOU'RE A RICH MAN"	            , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"BABY'S IN BLACK"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"BACK IN THE U.S.S.R."	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"BAD BOY"	                            , "writer":"Lennon	                                    ", "vocalist":"Instrumental*                                "},
    {"title":"BAD TO ME"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"THE BALLAD OF JOHN AND YOKO"	        , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"BEAUTIFUL DREAMER"	                , "writer":"Foster	                                    ", "vocalist":"McCartney	                                "},
    {"title":"BECAUSE"	                            , "writer":"Lennon	                                    ", "vocalist":"Lennon, McCartney, Harrison	                "},
    {"title":"BECAUSE I KNOW YOU LOVE ME SO"	    , "writer":"Lennon, McCartney	                        ", "vocalist":"Lennon, McCartney	                        "},
    {"title":"BEING FOR THE BENEFIT OF MR. KITE!"   , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"BÉSAME MUCHO"	                        , "writer":"Velázquez, Skylar	                        ", "vocalist":"McCartney	                                "},
    {"title":"BIRTHDAY"	                            , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"BLACKBIRD"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"BLUE JAY WAY"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"BOYS"	                                , "writer":"Dixon, Farrell	                            ", "vocalist":"Starkey (Best)	                            "},
//C
    {"title":"CAN'T BUY ME LOVE"	                , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"CARNIVAL OF LIGHT"	                , "writer":"McCartney	                                ", "vocalist":"*Instrumental*	                            "},
    {"title":"CAROL"	                            , "writer":"Lennon	                                    ", "vocalist":"*Instrumental*                               "},
    {"title":"CARRY THAT WEIGHT"	                , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon, Harrison and Starkey "},
    {"title":"CATSWALK"	                            , "writer":"McCartney	                                ", "vocalist":"*Instrumental	                            "},
    {"title":"CAYENNE"	                            , "writer":"McCartney	                                ", "vocalist":"*Instrumental	                            "},
    {"title":"CHAINS"	                            , "writer":"Goffin, King	                            ", "vocalist":"Harrison, with Lennon and McCartney	        "},
    {"title":"CHILD OF NATURE"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"CHRISTMAS TIME (IS HERE AGAIN)"	    , "writer":"Lennon, McCartney, Harrison and Starkey	    ", "vocalist":"Lennon, McCartney, Harrison and Starkey	    "},
    {"title":"CIRCLES"	                            , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"CLARABELLA"	                        , "writer":"Pingatore	                                ", "vocalist":"McCartney	                                "},
    {"title":"COME AND GET IT"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"COME TOGETHER"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"THE CONTINUING STORY OF BUNGALOW BILL", "writer":"Lennon	                                    ", "vocalist":"Lennon, with Starkey	                        "},
    {"title":"CRY BABY CRY"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"CRY FOR A SHADOW"	                    , "writer":"Lennon and Harrison	                        ", "vocalist":"*Instrumental*                               "},
    {"title":"CRYING, WAITING, HOPING"	            , "writer":"Buddy Holly	                                ", "vocalist":"Harrison	                                    "},
//D
    {"title":"A DAY IN THE LIFE"	                , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"DAY TRIPPER"	                        , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"DEAR PRUDENCE"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"DEVIL IN HER HEART"	                , "writer":"Drapkin (aka Ricky Dee)	                    ", "vocalist":"Harrison	                                    "},
    {"title":"DIG A PONY"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"DIG IT" 	                            , "writer":"Lennon, with McCartney, Harrison and Starkey", "vocalist":"Lennon	                                    "},
    {"title":"DIZZY, MISS LIZZY"	                , "writer":"Lennon	                                    ", "vocalist":"*Instrumental*                               "},
    {"title":"DO YOU WANT TO KNOW A SECRET?"	    , "writer":"Lennon	                                    ", "vocalist":"Harrison	                                    "},
    {"title":"DOCTOR ROBERT"	                    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"DON'T BOTHER ME"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"DON'T EVER CHANGE"	                , "writer":"Goffin, King	                            ", "vocalist":"Harrison	                                    "},
    {"title":"DON'T LET ME DOWN"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"DON'T PASS ME BY"	                    , "writer":"Starkey	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"DRIVE MY CAR"	                        , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
//E
    {"title":"EIGHT DAYS A WEEK"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"ELEANOR RIGBY"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"THE END"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"ETCETERA"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney   	                                "},
    {"title":"EVERY LITTLE THING"	                , "writer":"McCartney	                                ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"EVERYBODY'S GOT SOMETHING TO HIDE EXCEPT FOR ME AND MY MONKEY", "writer":"Lennon	            ", "vocalist":"Lennon	                                    "},
    {"title":"EVERYBODY'S TRYING TO BE MY BABY"	    , "writer":"Perkins	                                    ", "vocalist":"Harrison	                                    "},
//F
    {"title":"FIXING A HOLE"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"FLYING"	                            , "writer":"Lennon, McCartney, Harrison and Starkey	    ", "vocalist":"*Instrumental*	                            "},
    {"title":"THE FOOL ON THE HILL"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"FOR NO ONE"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"FOR YOU BLUE"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"FREE AS A BIRD"	                    , "writer":"Lennon, with McCartney, Harrison and Starkey", "vocalist":"Lennon, McCartney and Harrison	            "},
    {"title":"FROM ME TO YOU"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"FROM US TO YOU"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
//G
    {"title":"GET BACK"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"GETTING BETTER"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"GIRL"	                                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"GLAD ALL OVER"	                    , "writer":"Bennett, Tepper, Schroeder	                ", "vocalist":"Harrison	                                    "},
    {"title":"GLASS ONION"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"GOLDEN SLUMBERS"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"GOOD DAY SUNSHINE"	                , "writer":"McCartney	                                ", "vocalist":"McCartney   	                                "},
    {"title":"GOOD MORNING, GOOD MORNING"	        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"GOOD NIGHT"	                        , "writer":"Lennon	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"GOODBYE"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"GOT TO GET YOU INTO MY LIFE" 	        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
//H
    {"title":"HALLELUJAH, I LOVE HER SO"	        , "writer":"Charles	                                    ", "vocalist":"McCartney	                                "},
    {"title":"HAPPINESS IS A WARM GUN"	            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"A HARD DAY'S NIGHT"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"HEATHER"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HELLO, GOODBYE"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HELLO LITTLE GIRL"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"HELP!"	                            , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"HELTER SKELTER"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HER MAJESTY"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HERE COMES THE SUN"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"HERE, THERE AND EVERYWHERE"	        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HEY BULLDOG"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"HEY JUDE"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HIPPY HIPPY SHAKE"	                , "writer":"McCartney	                                ", "vocalist":"Instrumental*                                "},
    {"title":"HOLD ME TIGHT"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"HONEY DON'T"	                        , "writer":"Perkins	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"HONEY PIE"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"HOW DO YOU DO IT?"	                , "writer":"Murray	                                    ", "vocalist":"Lennon	                                    "},
//I
    {"title":"I AM THE WALRUS"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I CALL YOUR NAME"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I DON'T WANT TO SPOIL THE PARTY"	    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I FEEL FINE"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I FORGOT TO REMEMBER TO FORGET"	    , "writer":"Stan Kesler and Charlie Feathers	        ", "vocalist":"Harrison	                                    "},
    {"title":"I GOT A WOMAN"	                    , "writer":"Charles	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I GOT TO FIND MY BABY"	            , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I JUST DON'T UNDERSTAND"	            , "writer":"Wilkin, Westberry	                        ", "vocalist":"Lennon	                                    "},
    {"title":"I LOST MY LITTLE GIRL"	            , "writer":"McCartney	                                ", "vocalist":"Lennon	                                    "},
    {"title":"I ME MINE"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"I NEED YOU"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"I SAW HER STANDING THERE"	            , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"I SHOULD HAVE KNOWN BETTER"	        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I WANNA BE YOUR MAN"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"Starkey	                                    "},
    {"title":"I WANT TO HOLD YOUR HAND"	            , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"I WANT TO TELL YOU"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"I WANT YOU (SHE'S SO HEAVY)"	        , "writer":"Lennon, with Ono	                        ", "vocalist":"Lennon	                                    "},
    {"title":"I WILL"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"IF I FELL"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"IF I NEEDED SOMEONE"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"IF YOU'VE GOT TROUBLE"	            , "writer":"Lennon and McCartney	                    ", "vocalist":"Starkey	                                    "},
    {"title":"I'LL BE BACK"	                        , "writer":"Lennon	                                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"I'LL BE ON MY WAY"	                , "writer":"McCartney	                                ", "vocalist":"Lennon	                                    "},
    {"title":"I'LL CRY INSTEAD"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I'LL FOLLOW THE SUN"	                , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"I'LL GET YOU"	                        , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"I'LL KEEP YOU SATISFIED"	            , "writer":"McCartney, with Lennon	                    ", "vocalist":"Lennon and/or McCartney	                    "},
    {"title":"I'M A LOSER"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I'M DOWN"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"I'M GONNA SIT RIGHT DOWN AND CRY (OVER YOU)", "writer":"Thomas, Biggs	                        ", "vocalist":"Lennon	                                    "},
    {"title":"I'M HAPPY JUST TO DANCE WITH YOU"	    , "writer":"Lennon and McCartney	                    ", "vocalist":"Harrison	                                    "},
    {"title":"I'M IN LOVE"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I'M LOOKING THROUGH YOU"	            , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"I'M ONLY SLEEPING"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I'M SO TIRED"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I'M TALKING ABOUT YOU"	            , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"IN MY LIFE"	                        , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"IN SPITE OF ALL THE DANGER"	        , "writer":"McCartney and Harrison	                    ", "vocalist":"Lennon	                                    "},
    {"title":"THE INNER LIGHT"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"IT WON'T BE LONG"	                    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"IT'S ALL TOO MUCH"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"IT'S ONLY LOVE"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"I'VE GOT A FEELING"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"I'VE JUST SEEN A FACE"	            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
//J
    {"title":"JAZZ PIANO SONG"	                    , "writer":"McCartney, Starkey	                        ", "vocalist":"McCartney	                                "},
    {"title":"JESSIE'S DREAM"	                    , "writer":"Lennon, McCartney, Harrison, Starkey	    ", "vocalist":"*Instrumental*	                            "},
    {"title":"JOHNNY B. GOODE"	                    , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"JULIA"	                            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"JUNK"	                                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
//K
    {"title":"KANSAS CITY/HEY, HEY, HEY, HEY"	    , "writer":"Leiber, Stoller/Penniman	                ", "vocalist":"McCartney	                                "},
    {"title":"KEEP YOUR HANDS OFF MY BABY"	        , "writer":"Goffin, King	                            ", "vocalist":"Lennon	                                    "},
    {"title":"KOMM GIB MIR DEINE HAND"	            , "writer":"Lennon/McCartney/Nicolas/Hellmer	        ", "vocalist":"Lennon and McCartney	                        "},
//L
    {"title":"LADY MADONNA"	                        , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"LEAVE MY KITTEN ALONE"	            , "writer":"Turner, McDougall	                        ", "vocalist":"Lennon	                                    "},
    {"title":"LEND ME YOUR COMB"	                , "writer":"Twomey, Wise, Weisman	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"LET IT BE"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"LIKE DREAMERS DO"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"LITTLE CHILD"	                        , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"LONESOME TEARS IN MY EYES"	        , "writer":"J. Burnette, D. Burnette, Burlison, Mortimer", "vocalist":"Lennon	                                    "},
    {"title":"THE LONG AND WINDING ROAD"	        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"LONG, LONG, LONG"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"LONG TALL SALLY"	                    , "writer":"Blackwell, Johnson, Penniman	            ", "vocalist":"McCartney	                                "},
    {"title":"LOOKING GLASS"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"LOVE ME DO"	                        , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"LOVE OF THE LOVED"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"LOVE YOU TO"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"LOVELY RITA"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"LUCILLE"	                            , "writer":"Penniman, Collins	                        ", "vocalist":"McCartney	                                "},
    {"title":"LUCY IN THE SKY WITH DIAMONDS"	    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
//M
    {"title":"MADMAN"	                            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"MAGGIE MAE"	                        , "writer":"Arr. Lennon, McCartney, Harrison, Starkey	", "vocalist":"Lennon	                                    "},
    {"title":"MAGICAL MYSTERY TOUR"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"MAILMAN, BRING ME NO MORE BLUES"	    , "writer":"Row, Katz, Roberts, Clayton	                ", "vocalist":"Lennon	                                    "},
    {"title":"MARTHA MY DEAR"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"MATCHBOX"	                            , "writer":"Perkins, Jefferson	                        ", "vocalist":"Starkey (Best)	                            "},
    {"title":"MAXWELL'S SILVER HAMMER"	            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"MEAN MR. MUSTARD"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"MEMPHIS, TENNESSEE"	                , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"MICHELLE"	                            , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"MISERY"	                            , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"MONEY (THAT'S WHAT I WANT)"	        , "writer":"Gordy, Bradford	                            ", "vocalist":"Lennon	                                    "},
    {"title":"MOONLIGHT BAY"	                    , "writer":"Percy Wenrich, Edward Madden                ", "vocalist":"Lennon, McCartney, Harrison, Eric Morecambe, Ernie Wise"},
    {"title":"MOTHER NATURE'S SON"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"MR. MOONLIGHT"	                    , "writer":"Johnson	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"MY BONNIE"	                        , "writer":"Traditional, arr. Sheridan	                ", "vocalist":"Sheridan	                                    "},
//N
    {"title":"THE NIGHT BEFORE"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"NO REPLY"	                            , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"NORWEGIAN WOOD (THIS BIRD HAS FLOWN)" , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"NOT A SECOND TIME"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"NOT GUILTY"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"NOTHIN' SHAKIN' (BUT THE LEAVES ON THE TREES)", "writer":"Fontaine	                        ", "vocalist":"Harrison	                                    "},
    {"title":"NOWHERE MAN"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
//O
    {"title":"OB-LA-DI, OB-LA-DA"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"OCTOPUS'S GARDEN"	                    , "writer":"Starkey	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"OH! DARLING"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"OLD BROWN SHOE"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"ONE AFTER 909"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"ONE AND ONE IS TWO"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"ONLY A NORTHERN SONG"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"OOH! MY SOUL"	                        , "writer":"Penniman	                                ", "vocalist":"McCartney	                                "},
//P
    {"title":"PAPERBACK WRITER"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney                                    "},
    {"title":"PENNY LANE"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"PIGGIES"	                            , "writer":"Harrison	                                ", "vocalist":"Harrison                                     "},
    {"title":"PLEASE MR. POSTMAN"	                , "writer":"Dobbins, Garrett, Holland, Bateman, Gorman	", "vocalist":"Lennon	                                    "},
    {"title":"PLEASE PLEASE ME"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"POLYTHENE PAM"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"P.S. I LOVE YOU"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
//R
    {"title":"RAIN"	                                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"REAL LOVE"	                        , "writer":"Lennon, with McCartney, Harrison, Starkey	", "vocalist":"Lennon	                                    "},
    {"title":"REVOLUTION"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"REVOLUTION 1"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"REVOLUTION 9"	                        , "writer":"Lennon, with Ono and Harrison	            ", "vocalist":"*Instrumental                                "},
    {"title":"RIP IT UP/SHAKE, RATTLE, AND ROLL/BLUE SUEDE SHOES", "writer":"Blackwell-Marascalco, Calhoun, Perkins", "vocalist":"Lennon and McCartney                  "},
    {"title":"ROCK AND ROLL MUSIC"	                , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"ROCKY RACCOON"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"ROLL OVER BEETHOVEN"	                , "writer":"Berry	                                    ", "vocalist":"Harrison	                                    "},
    {"title":"RUN FOR YOUR LIFE"	                , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
//S
    {"title":"THE SAINTS"	                        , "writer":"Traditional, arr. Sheridan	                ", "vocalist":"Sheridan	                                    "},
    {"title":"SAVOY TRUFFLE"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison 	                                "},
    {"title":"SEARCHIN'"	                        , "writer":"Leiber, Stoller	                            ", "vocalist":"McCartney	                                "},
    {"title":"SEPTEMBER IN THE RAIN"	            , "writer":"Al Dubin, Harry Warren	                    ", "vocalist":"McCartney	                                "},
    {"title":"SEXY SADIE"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"SGT. PEPPER'S LONELY HEARTS CLUB BAND", "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"SGT. PEPPER'S LONELY HEARTS CLUB BAND (REPRISE)", "writer":"McCartney	                        ", "vocalist":"McCartney, with Lennon and Harrison	        "},
    {"title":"SHAKIN' IN THE SIXTIES"	            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"SHE CAME IN THROUGH THE BATHROOM WINDOW", "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"SHE LOVES YOU"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"SHE SAID SHE SAID"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"SHE'S A WOMAN"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"SHE'S LEAVING HOME"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"THE SHEIK OF ARABY"	                , "writer":"Smith, Wheeler-Snyder	                    ", "vocalist":"Harrison	                                    "},
    {"title":"A SHOT OF RHYTHM AND BLUES"	        , "writer":"Terry Thompson	                            ", "vocalist":"Lennon	                                    "},
    {"title":"SHOUT"	                            , "writer":"Isley, Isley, Isley	                        ", "vocalist":"Lennon, McCartney, Harrison and Starkey	    "},
    {"title":"SIE LIEBT DICH"	                    , "writer":"Lennon and McCartney/Nicolas/Montague	    ", "vocalist":"Lennon–McCartney	                            "},
    {"title":"SLOW DOWN"	                        , "writer":"Williams	                                ", "vocalist":"Lennon	                                    "},
    {"title":"SO HOW COME (NO ONE LOVES ME)"	    , "writer":"Bryant, Bryant	                            ", "vocalist":"Harrison	                                    "},
    {"title":"SOLDIER OF LOVE (LAY DOWN YOUR ARMS)" , "writer":"Cason, Moon	                                ", "vocalist":"Lennon	                                    "},
    {"title":"SOME OTHER GUY"	                    , "writer":"Leiber, Stoller, Barrett	                ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"SOMETHING"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"SOUR MILK SEA"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"STEP INSIDE LOVE/LOS PARANOIAS"	    , "writer":"Lennon, McCartney, Harrison and Starkey 	", "vocalist":"McCartney	                                "},
    {"title":"STRAWBERRY FIELDS FOREVER"	        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"SUN KING"	                            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"SURE TO FALL (IN LOVE WITH YOU)"	    , "writer":"Perkins, Claunch, Cantrell	                ", "vocalist":"McCartney	                                "},
    {"title":"SWEET LITTLE SIXTEEN"	                , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
//T
    {"title":"TAKE GOOD CARE OF MY BABY"	        , "writer":"Goffin, King	                            ", "vocalist":"Harrison	                                    "},
    {"title":"TAKING A TRIP TO CAROLINA"	        , "writer":"Starkey	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"A TASTE OF HONEY"	                    , "writer":"Scott, Marlow	                            ", "vocalist":"McCartney	                                "},
    {"title":"TAXMAN"	                            , "writer":"Harrison uncredited contribution from Lennon", "vocalist":"Harrison	                                    "},
    {"title":"TEDDY BOY"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"TELL ME WHAT YOU SEE"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"TELL ME WHY"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"THANK YOU GIRL"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"THAT MEANS A LOT"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"THAT'LL BE THE DAY"	                , "writer":"Allison, Holly, Petty	                    ", "vocalist":"Lennon	                                    "},
    {"title":"THAT'S ALL RIGHT (MAMA)"	            , "writer":"Crudup	                                    ", "vocalist":"McCartney	                                "},
    {"title":"THE HONEYMOON SONG"	                , "writer":"Theodorakis, Sansom	                        ", "vocalist":"McCartney	                                "},
    {"title":"THERE'S A PLACE"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"THINGS WE SAID TODAY"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"THINK FOR YOURSELF"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"THIS BOY"	                            , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney and Harrison	        "},
    {"title":"THREE COOL CATS"	                    , "writer":"Leiber, Stoller	                            ", "vocalist":"Harrison	                                    "},
    {"title":"TICKET TO RIDE"	                    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"TILL THERE WAS YOU"	                , "writer":"Willson	                                    ", "vocalist":"McCartney	                                "},
    {"title":"TIP OF MY TONGUE"	                    , "writer":"Lennon and/or McCartney	                    ", "vocalist":"McCartney/Lennon	                            "},
    {"title":"TO KNOW HER IS TO LOVE HER"	        , "writer":"Spector	                                    ", "vocalist":"Lennon 	                                    "},
    {"title":"TOMORROW NEVER KNOWS"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"TOO MUCH MONKEY BUSINESS"	            , "writer":"Berry	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"TWIST AND SHOUT"	                    , "writer":"Medley, Russell	                            ", "vocalist":"Lennon	                                    "},
    {"title":"TWO OF US"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon	                    "},
//W
    {"title":"WAIT"	                                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon 	                    "},
    {"title":"WATCHING RAINBOWS"	                , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"WE CAN WORK IT OUT"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"WHAT GOES ON"	                        , "writer":"Lennon and McCartney, with Starkey	        ", "vocalist":"Starkey	                                    "},
    {"title":"WHAT YOU'RE DOING"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"WHAT'S THE NEW MARY JANE"	            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"WHEN I GET HOME"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"WHEN I'M SIXTY-FOUR"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"WHILE MY GUITAR GENTLY WEEPS"	        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"WHY DON'T WE DO IT IN THE ROAD?"	    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"WILD HONEY PIE"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"WINSTON'S WALK"	                    , "writer":"Lennon	                                    ", "vocalist":"*Insturmental*	                            "},
    {"title":"WITH A LITTLE HELP FROM MY FRIENDS"   , "writer":"McCartney, with Lennon	                    ", "vocalist":"Starkey	                                    "},
    {"title":"WITHIN YOU WITHOUT YOU"	            , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"WOMAN"	                            , "writer":"McCartney (as Bernard Webb or A. Smith)	    ", "vocalist":"McCartney	                                "},
    {"title":"THE WORD"	                            , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon, McCartney and Harrison	            "},
    {"title":"WORDS OF LOVE"	                    , "writer":"Holly	                                    ", "vocalist":"Lennon and McCartney	                        "},
//Y
    {"title":"YELLOW SUBMARINE"	                    , "writer":"McCartney	                                ", "vocalist":"Starkey	                                    "},
    {"title":"YER BLUES"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"YES IT IS"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon, McCartney and Harrison	            "},
    {"title":"YESTERDAY"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"YOU CAN'T DO THAT"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"YOU KNOW MY NAME(LOOK UP THE NUMBER)" , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"YOU KNOW WHAT TO DO"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"YOU LIKE ME TOO MUCH"	                , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"YOU NEVER GIVE ME YOUR MONEY"	        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"YOU WON'T SEE ME"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"YOU'LL BE MINE"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"McCartney	                                "},
    {"title":"YOUNG BLOOD"	                        , "writer":"Leiber, Stoller	                            ", "vocalist":"Harrison	                                    "},
    {"title":"YOUR MOTHER SHOULD KNOW"	            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"YOU'RE GOING TO LOSE THAT GIRL"	    , "writer":"Lennon	                                    ", "vocalist":"Lennon 	                                    "},
    {"title":"YOU'VE GOT TO HIDE YOUR LOVE AWAY"	, "writer":"Lennon	                                    ", "vocalist":"Lennon 	                                    "},
    {"title":"YOU'VE REALLY GOT A HOLD ON ME"	    , "writer":"Robinson	                                ", "vocalist":"Lennon and Harrison	                        "}
];
