
var songs = [
    {"title":"12-Bar Original"                      , "writer":"Lennon, McCartney, Harrison and Starkey     ", "vocalist":"Instrumental                                 "},
    {"title":"Across the Universe"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Act Naturally"	                    , "writer":"Russell, Morrison                           ", "vocalist":"Starkey                                      "},
    {"title":"Ain't She Sweet"	                    , "writer":"Yellen, Ager	                            ", "vocalist":"Lennon	                                    "},
    {"title":"All I've Got to Do"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon                                       "},
    {"title":"All My Loving"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney                                    "},
    {"title":"All Things Must Pass"	                , "writer":"Harrison	—	—                           ", "vocalist":"                                             "},
    {"title":"All Together Now"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"All You Need Is Love"	                , "writer":"Lennon                                      ", "vocalist":"Lennon                                       "},
    {"title":"And I Love Her"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"And Your Bird Can Sing"               , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"Anna (Go to Him)"	                    , "writer":"Alexander	                                ", "vocalist":"Lennon	                                    "},
    {"title":"Another Girl"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Any Time at All"	                    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"Ask Me Why"	                        , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon 	                                    "},
    {"title":"Baby It's You"	                    , "writer":"Bacharach, David, Dixon	                    ", "vocalist":"Lennon	                                    "},
    {"title":"Baby, You're a Rich Man"	            , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"Baby's in Black"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"Back in the U.S.S.R."	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Bad Boy"	                            , "writer":"Lennon	                                    ", "vocalist":"                                             "},
    {"title":"Bad to Me"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"The Ballad of John and Yoko"	        , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"Beautiful Dreamer"	                , "writer":"Foster	                                    ", "vocalist":"McCartney	                                "},
    {"title":"Because"	                            , "writer":"Lennon	                                    ", "vocalist":"Lennon, McCartney, Harrison	                "},
    {"title":"Because I Know You Love Me So"	    , "writer":"Lennon, McCartney	                        ", "vocalist":"Lennon, McCartney	                        "},
    {"title":"Being for the Benefit of Mr. Kite!"   , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"Bésame Mucho"	                        , "writer":"Velázquez, Skylar	                        ", "vocalist":"McCartney	                                "},
    {"title":"Birthday"	                            , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"Blackbird"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Blue Jay Way"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"Boys"	                                , "writer":"Dixon, Farrell	                            ", "vocalist":"Starkey (Best)	                            "},
    {"title":"Can't Buy Me Love"	                , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"Carnival of Light"	                , "writer":"McCartney	                                ", "vocalist":"N/A	                                        "},
    {"title":"Carol"	                            , "writer":"Lennon	                                    ", "vocalist":"                                             "},
    {"title":"Carry That Weight"	                , "writer":"McCartney	                                ", "vocalist":"McCartney, with Lennon, Harrison and Starkey "},
    {"title":"Catswalk"	                            , "writer":"McCartney	                                ", "vocalist":"N/A	                                        "},
    {"title":"Cayenne"	                            , "writer":"McCartney	                                ", "vocalist":"N/A	                                        "},
    {"title":"Chains"	                            , "writer":"Goffin, King	                            ", "vocalist":"Harrison, with Lennon and McCartney	        "},
    {"title":"Child of Nature"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Christmas Time (Is Here Again)"	    , "writer":"Lennon, McCartney, Harrison and Starkey	    ", "vocalist":"Lennon, McCartney, Harrison and Starkey	    "},
    {"title":"Circles"	                            , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"Clarabella"	                        , "writer":"Pingatore	                                ", "vocalist":"McCartney	                                "},
    {"title":"Come and Get It"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Come Together"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"The Continuing Story of Bungalow Bill", "writer":"Lennon	                                    ", "vocalist":"Lennon, with Starkey	                        "},
    {"title":"Cry Baby Cry"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"Cry for a Shadow"	                    , "writer":"Lennon and Harrison	N/A	—	—               ", "vocalist":"                                             "},
    {"title":"Crying, Waiting, Hoping"	            , "writer":"Buddy Holly	                                ", "vocalist":"Harrison	                                    "},
    {"title":"A Day in the Life"	                , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"Day Tripper"	                        , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"Dear Prudence"	                    , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Devil in Her Heart"	                , "writer":"Drapkin (aka Ricky Dee)	                    ", "vocalist":"Harrison	                                    "},
    {"title":"Dig a Pony"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Dig It" 	                            , "writer":"Lennon, with McCartney, Harrison and Starkey", "vocalist":"Lennon	                                    "},
    {"title":"Dizzy, Miss Lizzy"	                , "writer":"Lennon	                                    ", "vocalist":"                                             "},
    {"title":"Do You Want to Know a Secret?"	    , "writer":"Lennon	                                    ", "vocalist":"Harrison	                                    "},
    {"title":"Doctor Robert"	                    , "writer":"Lennon, with McCartney	                    ", "vocalist":"Lennon	                                    "},
    {"title":"Don't Bother Me"	                    , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"Don't Ever Change"	                , "writer":"Goffin, King	                            ", "vocalist":"Harrison	                                    "},
    {"title":"Don't Let Me Down"	                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Don't Pass Me By"	                    , "writer":"Starkey	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"Drive My Car"	                        , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney, with Lennon	                    "},
    {"title":"Eight Days a Week"	                , "writer":"McCartney, with Lennon	                    ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"Eleanor Rigby"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"The End"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Etcetera"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney   	                                "},
    {"title":"Every Little Thing"	                , "writer":"McCartney	                                ", "vocalist":"Lennon, with McCartney	                    "},
    {"title":"Everybody's Got Monkey"	            , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Everybody's Trying to Be My Baby"	    , "writer":"Perkins	                                    ", "vocalist":"Harrison	                                    "},
    {"title":"Fixing a Hole"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Flying"	                            , "writer":"Lennon, McCartney, Harrison and Starkey	    ", "vocalist":"N/A	                                        "},
    {"title":"The Fool on the Hill"	                , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"For No One"	                        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"For You Blue"	                        , "writer":"Harrison	                                ", "vocalist":"Harrison	                                    "},
    {"title":"Free as a Bird"	                    , "writer":"Lennon, with McCartney, Harrison and Starkey", "vocalist":"Lennon, McCartney and Harrison	            "},
    {"title":"From Me to You"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"From Us to You"	                    , "writer":"Lennon and McCartney	                    ", "vocalist":"Lennon and McCartney	                        "},
    {"title":"Get Back"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Getting Better"	                    , "writer":"McCartney, with Lennon	                    ", "vocalist":"McCartney	                                "},
    {"title":"Girl"	                                , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Glad All Over"	                    , "writer":"Bennett, Tepper, Schroeder	                ", "vocalist":"Harrison	                                    "},
    {"title":"Glass Onion"	                        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Golden Slumbers"	                    , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Good Day Sunshine"	                , "writer":"McCartney	                                ", "vocalist":"McCartney   	                                "},
    {"title":"Good Morning, Good Morning"	        , "writer":"Lennon	                                    ", "vocalist":"Lennon	                                    "},
    {"title":"Good Night"	                        , "writer":"Lennon	                                    ", "vocalist":"Starkey	                                    "},
    {"title":"Goodbye"	                            , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},
    {"title":"Got to Get You into My Life" 	        , "writer":"McCartney	                                ", "vocalist":"McCartney	                                "},


    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"},
    {"title":"title", "writer":"writer", "vocalist":"vocalist"}



];